BakkalUygulamasi/BakkalUygulamasi.webui/Controllers/HesapController.cs
using BakkalUygulamasi.entity.Data;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BakkalUygulamasi.webui.Controllers
{
    
    public class HesapController:Controller

    {
       
        BakkalDbContext context = new BakkalDbContext();
        
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        
        //Authentication işlemleri için geliştirmiş olduğumuz Login isimli post http istek türünde controller methodumuz.Authentication ile kullanıcılar için kimlik 
        //doğrulama işlemleri başarılı bir şekilde yürütülmektedir.
        [HttpPost]
        public async Task<IActionResult> Login(Kullanici kullanici)
        {
            //Web sayfasının login bölümünde giriş bilgilerini giren kullanıcıların kimlik doğrulama işlemlerinin yapılması 
            var user = context.Kullanicis.FirstOrDefault(x => x.KKullaniciadi == kullanici.KKullaniciadi && x.KParola == kullanici.KParola);

            //Kullanıcı veri tabanında kayıtlı ise authorization işlemi başarıyla yürütülür ve kullanıcının authentication yapmış olması sağlanır.
            if (user != null)
            {

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,kullanici.KKullaniciadi)
                };

                var useridentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                //Kimlik doğrulaması başarıyla gerçekleşmiş kullanıcı, home controller altında bulunan Index methoduna yöneltilir.
                return Redirect("/Home/Index/" + user.KullaniciId);
             
            }

            //Eğer giriş bilgileri girilen kullanıcı veri tabanında bulunamamışsa Authentication işlemi başarısız sonuçlanır ve kullanıcı login sayfasına tekrardan yönlendirilir.
            else
            {
                ViewBag.Mesaj=("Geçersiz kullanıcı adı veya şifre");
                return View();
            }
            
       //Sistemden çıkış için controller methodu
        }
        [HttpGet]
        public async Task< IActionResult> Logout()
        {
            //Cookieleri geçersiz kılıyoruz ve böylelikle kullanıcının giriş bilgileri sistemden siliniyor.
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
            public IActionResult KullaniciEkle()
            {
                return View();
            }


        //Sisteme kullanıcı kayıt aşaması
        [HttpPost]
        public IActionResult KullaniciEkle(Kullanici user)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz parametre bilgilerini kullanarak kullanıcı ekleme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw("exec proc_kullanici_insert @k_kullaniciadi={0},@k_parola={1},@k_adi={2},@k_soyadi={3},@k_eposta={4},@k_telefon={5},@k_durum={6},@rol_id={7}",  user.KKullaniciadi, user.KParola, user.KAdi, user.KSoyadi, user.KEposta, user.KTelefon, user.KDurum, user.RolId);
            return Redirect("/Hesap/KullaniciListesi");
        }

        //Veri tabanından kullanıcı silmek için yazmış olduğumuz bir controller methodur. silinecek olan kullanıcıya ait kullanıcı id numrasını parametre olarak alır
        public IActionResult KullaniciSil(int kullaniciId)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, seçmiş olduğumuz kullanıcının id bilgisini kullanarak veri tabanından kullanıcı silme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw($"proc_kullanici_delete {kullaniciId}");
            return Redirect("/Hesap/KullaniciListesi");
        }


        public IActionResult KullaniciListesi()
        {
            List<Kullanici> model = new List<Kullanici>();
            BakkalDbContext context = new BakkalDbContext();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden bize kullanıcıların listesini dönecek olan procedürü çağırırız
            model = context.Kullanicis.FromSqlRaw<Kullanici>($"exec proc_kullanici_list").ToList();
            //Views'da bulunan KullaniciListesi.cshtml dosyasına model bilgisi atılır.
            return View(model);
        }

        //Kullanıcı bilgilerini güncellemek için yazmış olduğumuz bir get http türlü controller methodur
        [HttpGet]
        public IActionResult KullaniciGuncelle(int kullaniciId)
        {
            BakkalDbContext context = new BakkalDbContext();
            Kullanici user = new Kullanici();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz id bilgisine göre bize veri tabanında bulunan ilgili kayıdı getiren procedürü çağırırız
            user = context.Kullanicis.FromSqlRaw($"exec proc_kullanici_get_by_id {kullaniciId}").AsEnumerable().FirstOrDefault();
            if (user == null)    //eğer herhangi bir kullanıcı kaydı bulunamamışsa sayfa bulunamadı döndürülür
            {
                return NotFound();
            }
            return View(user);
        }

        //Kullanıcı bilgilerini güncellemek için yazmış olduğumuz bir post http türlü controller methodur
        [HttpPost]
        public IActionResult KullaniciGuncelle(Kullanici user)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz parametre bilgilerini kullanarak kullanıcı bilgilerinde güncelleme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw("exec proc_kullanici_update @kullanici_id={0}, @k_kullaniciadi={1},@k_parola={2},@k_adi={3},@k_soyadi={4},@k_eposta={5},@k_telefon={6},@k_durum={7},@rol_id={8}",user.KullaniciId,user.KKullaniciadi,user.KParola,user.KAdi,user.KSoyadi,user.KEposta,user.KTelefon,user.KDurum,user.RolId);
            return Redirect("/Hesap/KullaniciListesi");
        }
        [HttpGet]
        public IActionResult RolEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RolEkle(Rol role)
        {
            BakkalDbContext context = new BakkalDbContext();
            var prm1 = new SqlParameter("@r_adi", role.RAdi);
            var data = context.Database.ExecuteSqlRaw("exec proc_rol_insert @r_adi={0}", role.RAdi);
            return Redirect("/Hesap/RolListesi");
        }
        public IActionResult RolSil(int rolId)
        {
            BakkalDbContext context = new BakkalDbContext();
            var data = context.Database.ExecuteSqlRaw($"proc_rol_delete {rolId}");
            return Redirect("/Hesap/RolListesi");
        }
        public IActionResult RolListesi()
        {
            List<Rol> model = new List<Rol>();
            BakkalDbContext context = new BakkalDbContext();
            model = context.Rols.FromSqlRaw<Rol>($"exec proc_rol_list").ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult RolGuncelle(int rolId)
        {
            BakkalDbContext context = new BakkalDbContext();
            Rol role = new Rol();
            role = context.Rols.FromSqlRaw($"exec proc_rol_get_by_id {rolId}").AsEnumerable().FirstOrDefault();
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }
        [HttpPost]
        public IActionResult RolGuncelle(Rol role)
        {
            BakkalDbContext context = new BakkalDbContext();
          
            var data = context.Database.ExecuteSqlRaw("exec proc_rol_update @rol_id={0}, @r_adi={1}",role.RolId,role.RAdi);
            return Redirect("/Hesap/RolListesi");
        }
    }
}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/KullaniciEkle.cshtml
@model BakkalUygulamasi.entity.Data.Kullanici

<!doctype html>
<html>
<head>
    
    <meta charset="utf-8" />
    <link href="~/css/kayit.css" rel="stylesheet">
   
</head>
<body>
    <div id="kayitFormu">
        <form asp-controller="Hesap" asp-action="KullaniciEkle" method="POST">
            <h3><d1 class="text-success">KULLANICI KAYIT FORMU</d1></h3>
            <img class="mb-4" src="~/img/kayit.png" alt="" height="100">

            <input class="form-control" asp-for="@Model.KAdi" placeholder="İsim" />
            <input class="form-control" asp-for="@Model.KSoyadi" placeholder="Soyisim" />
            <input class="form-control" asp-for="@Model.KKullaniciadi" placeholder="Kullanıcı Adı" />
            <input class="form-control" asp-for="@Model.KParola" placeholder="Parola" />
            <input class="form-control" asp-for="@Model.KEposta" placeholder="E-Mail" />
            <input class="form-control" asp-for="@Model.KTelefon" placeholder="Telefon Numarası" />
            <input class="form-control" asp-for="@Model.RolId" placeholder="Rol Id" />
            <button type="submit" class="btn btn-success">Kayıt Ol</button>
        </form>

    </div>


</body>
</html>

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/KullaniciGuncelle.cshtml
@model BakkalUygulamasi.entity.Data.Kullanici
<!doctype html>
<html>
<head>

    <meta charset="utf-8" />
    <link href="~/css/kayit.css" rel="stylesheet">

</head>
<body>
    <div id="kayitFormu">
        <form asp-controller="Hesap" asp-action="KullaniciGuncelle" method="POST">
            <input type="hidden" name="kullaniciId" value="@Model.KullaniciId" />
            <h3><d1 class="text-success">KULLANICI GÜNCELLEME FORMU</d1></h3>
            <img class="mb-4" src="~/img/kayit.png" alt="" height="100">

            <input class="form-control" asp-for="@Model.KAdi" placeholder="İsim" />
            <input class="form-control" asp-for="@Model.KSoyadi" placeholder="Soyisim" />
            <input class="form-control" asp-for="@Model.KKullaniciadi" placeholder="Kullanıcı Adı" />
            <input class="form-control" asp-for="@Model.KParola" placeholder="Parola" />
            <input class="form-control" asp-for="@Model.KEposta" placeholder="E-Mail" />
            <input class="form-control" asp-for="@Model.KTelefon" placeholder="Telefon Numarası" />
            <input class="form-control" asp-for="@Model.RolId" placeholder="Rol Id" />
            <button type="submit" class="btn btn-success">Güncelle</button>
        </form>

    </div>


</body>
</html>

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/KullaniciListesi.cshtml
@model List<BakkalUygulamasi.entity.Data.Kullanici>
<div class="w-100">
    <div class="row">
        <div class="com-md-12">
            <h1 class="h3">Kullanıcılar</h1>
            <hr />
            <a class="btn btn-primary btn-sm" href="/hesap/kullanıcı/ekle">Kullanıcı Ekle</a>
            <table class="table table-bordered mt-3">
                <thead>
                    <tr>
                        <td style="width:70px;">Id</td>
                        <td style="width:1000px">İsim</td>
                        <td style="width:170px;">Soyisim</td>
                        <td style="width:170px;">Kullanıcı Adı</td>
                        <td style="width:170px;">Parola</td>
                        <td style="width:170px;">Eposta</td>
                        <td style="width:170px;">Telefon</td>
                        <td style="width:170px;">Rol Id</td>
            
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.KullaniciId</td>
                        <td>@item.KAdi</td>
                        <td>@item.KSoyadi</td>
                        <td>@item.KKullaniciadi</td>
                        <td>@item.KParola</td>
                        <td>@item.KEposta</td>
                        <td>@item.KTelefon</td>
                        <td>@item.RolId</td>
                        <td>
                            <a href="/hesap/kullanıcı/guncelle/@item.KullaniciId" class="btn btn-primary btn-sm mr-2">Düzenle</a>

                            <form action="/hesap/kullanicisil" method="POST" style="display:inline">
                                <input type="hidden" name="kullaniciId" value="@item.KullaniciId" />
                                <button type="submit" class="btn btn-danger btn-sm">Sil</button>
                            </form>
                        </td>
                    </tr>
                    }


                </tbody>
            </table>

        </div>
    </div>
</div>

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/Login.cshtml
@model BakkalUygulamasi.entity.Data.Kullaniciler

<html lang="en">
<head>
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Bakkal Uygulaması</title>
    <link href="~/css/login.css" rel="stylesheet">
</head>

<body class="text-center">
    <main class="form-signin">
        <form asp-controller="Hesap" asp-action="Login" method="POST">
            
            <img class="mb-4" src="~/img/logo.png" alt="" height="100">
            <h1 class="h3 mb-3 fw-normal"><b>Bakkal Uygulaması</b> Giriş Yap</h1>

            <div class="form-floating">
                <input class="form-control" asp-for="KKullaniciadi" />
                <label asp-for="KKullaniciadi" class="col-form-label">Kullanıcı Adı</label>
            </div>
            <div class="form-floating">
                <input class="form-control" asp-for="KParola" />
                <label asp-for="KParola" class="col-form-label">Parola</label>
            </div>

            <button type="submit" class="w-100 btn btn-lg btn-primary mt-3">Giriş Yap</button>
            @ViewBag.Mesaj
        </form>
    </main>

    <script src="login.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.16/dist/sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/RolEkle.cshtml
@model BakkalUygulamasi.entity.Data.Rol
<h1 class="h3 mt-4">Rol Ekleme</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Hesap" asp-action="RolEkle" method="POST">
                <div class="form-group row">
                    <label asp-for="@Model.RAdi" class="col-sm col-form-label"><b>Rol Adı</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.RAdi" />
                      
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/RolGuncelle.cshtml
@model BakkalUygulamasi.entity.Data.Rol
<h1 class="h3 mt-4">Rol Güncelle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Hesap" asp-action="RolGuncelle" method="POST">
                <input type="hidden" name="rolId" value="@Model.RolId" />
                <div class="form-group row">
                    <label asp-for="@Model.RAdi" class=" col-form-label"><b>Rol İsmi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.RAdi" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Güncelle</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Hesap/RolListesi.cshtml
@model List<BakkalUygulamasi.entity.Data.Rol>
<div class="w-100">
    <div class="row">
        <div class="com-md-12">
            <h1 class="h3">Roller</h1>
            <hr />
            <a class="btn btn-primary btn-sm" href="/hesap/rol/ekle">Rol Ekle</a>
            <table class="table table-bordered mt-3">
                <thead>
                    <tr>
                        <td style="width:70px;">Id</td>
                        <td style="width:1000px">Rol Adı</td>
                        <td style="width:170px;"></td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.RolId</td>
                            <td>@item.RAdi</td>
                            <td>
                                <a href="/hesap/rol/guncelle/@item.RolId" class="btn btn-primary btn-sm mr-2">Düzenle</a>

                                <form action="/hesap/rolsil" method="POST" style="display:inline">
                                    <input type="hidden" name="rolId" value="@item.RolId" />
                                    <button type="submit" class="btn btn-danger btn-sm">Sil</button>
                                </form>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>

        </div>
    </div>
</div>