BakkalUygulamasi/BakkalUygulamasi.webui/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.Data.SqlClient;

using Microsoft.EntityFrameworkCore;
using BakkalUygulamasi.entity.Data;

using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace BakkalUygulamasi.webui.Controllers
{
    [Authorize]
    public class PersonelController:Controller
    {

       //Kategori listesini döndüren controller methodudur
        public IActionResult KategoriListesi() 
        {
            List<Kategori> model = new List<Kategori>();
            BakkalDbContext context = new BakkalDbContext();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden bize kategori listesini dönecek olan procedürü çağırırız
            model = context.Kategoris.FromSqlRaw<Kategori>($"exec proc_kategori_list").ToList();
            //Views'da bulunan KategoriListesi.cshtml dosyasına model bilgisi atılır.
            return View(model);
        }

        //Kategori bilgilerini güncellemek için yazmış olduğumuz bir get http türlü controller methodur
         [HttpGet]
        public IActionResult KategoriGuncelle(int KategoriId)
        {
            BakkalDbContext context = new BakkalDbContext();
            Kategori category=new Kategori();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz id bilgisine göre bize veri tabanında bulunan ilgili kayıdı getiren procedürü çağırırız
            category = context.Kategoris.FromSqlRaw($"exec proc_kategori_get_by_id {KategoriId}").AsEnumerable().FirstOrDefault();
            if (category == null)
            {
                return NotFound();
            }
            //Views'da bulunan KategoriListesi.cshtml dosyasına procedürden döndürülen kayıdın bilgisi atılır.
            return View(category);
        }

        //Kategori bilgilerini güncellemek için yazmış olduğumuz bir post http türlü controller methodur
        [HttpPost]
        public IActionResult KategoriGuncelle(Kategori category)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz parametre bilgilerini kullanarak kategori bilgilerinde güncelleme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw("proc_kategori_update @kategori_id={0} ,@k_adi={1}",category.KategoriId,category.KAdi);
            //kullanıcıyı personel kategori listesi sayfasına yönlendirir
            return Redirect("/Personel/KategoriListesi");
        }

        //Veri tabanından kategori silmek için yazmış olduğumuz bir controller methodur. silinecek olan kategorinin id numrasını parametre olarak alır
        public IActionResult KategoriSil(int kategoriId)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, seçmiş olduğumuz kategorinin id bilgisini kullanarak veri tabanından kategori silme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw($"proc_kategori_delete {kategoriId}");
            return Redirect("/Personel/KategoriListesi");
        }

        //Kategori bilgileri eklemek için yazmış olduğumuz bir get http türlü controller methodur
        [HttpGet]
        public IActionResult KategoriEkle()
        {
            return View();
        }
        //Kategori bilgileri eklemek için yazmış olduğumuz bir post http türlü controller methodur
        [HttpPost]
        public IActionResult KategoriEkle(Kategori category)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz parametre bilgilerini kullanarak kategori ekleme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw("exec proc_kategori_insert @k_adi= {0}",category.KAdi);
            return Redirect("/Personel/KategoriListesi");
        }

        //Marka bilgileri eklemek için yazmış olduğumuz bir get http türlü controller methodur
        [HttpGet]
        public IActionResult MarkaEkle()
        {
            return View();
        }
        //Marka bilgileri eklemek için yazmış olduğumuz bir post http türlü controller methodur
        [HttpPost]
        public IActionResult MarkaEkle(Marka brand)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz parametre bilgilerini kullanarak marka ekleme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw("exec proc_marka_insert @m_adi={0}",brand.MAdi);
            return Redirect("/Personel/MarkaListesi");
        }


        //Veri tabanından marka silmek için yazmış olduğumuz bir controller methodur. silinecek olan markanın id numrasını parametre olarak alır
        public IActionResult MarkaSil(int markaId)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, seçmiş olduğumuz stoğun id bilgisini kullanarak veri tabanından stok silme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw($"proc_marka_delete {markaId}");
            return Redirect("/Personel/MarkaListesi");
        }

        //Marka listesini döndüren controller methodudur
        public IActionResult MarkaListesi()
        {
            List<Marka> model = new List<Marka>();
            BakkalDbContext context = new BakkalDbContext();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden bize marka listesini dönecek olan procedürü çağırırız
            model = context.Markas.FromSqlRaw<Marka>($"exec proc_marka_list").ToList();
            //Views'da bulunan MarkaListesi.cshtml dosyasına model bilgisi atılır.
            return View(model);
        }

        //Marka bilgilerini güncellemek için yazmış olduğumuz bir get http türlü controller methodur
        [HttpGet]
        public IActionResult MarkaGuncelle(int MarkaId)
        {
            BakkalDbContext context = new BakkalDbContext();
            Marka brand = new Marka();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz id bilgisine göre bize veri tabanında bulunan ilgili kayıdı getiren procedürü çağırırız
            brand = context.Markas.FromSqlRaw($"exec proc_marka_get_by_id {MarkaId}").AsEnumerable().FirstOrDefault();
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }
        //Marka bilgilerini güncellemek için yazmış olduğumuz bir post http türlü controller methodur
        [HttpPost]
        public IActionResult MarkaGuncelle(Marka brand)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz parametre bilgilerini kullanarak marka bilgilerinde güncelleme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw("proc_marka_update @marka_id={0}, @m_adi={1}",brand.MarkaId,brand.MAdi);
            return Redirect("/Personel/MarkaListesi");
        }

        //Stok bilgileri eklemek için yazmış olduğumuz bir get http türlü controller methodur
        [HttpGet]
        public IActionResult StokEkle()
        {
            return View();
        }
        //Stok bilgileri eklemek için yazmış olduğumuz bir post http türlü controller methodur
        [HttpPost]
        public IActionResult StokEkle(Stok stock)
        {
            BakkalDbContext context = new BakkalDbContext();

            var data = context.Database.ExecuteSqlRaw("exec proc_stok_insert @s_adedi= {0}, @s_giris_tarihi = {1}, @s_bitis_tarihi={2}",stock.SAdedi,stock.SGirisTarihi,stock.SBitisTarihi);
            return Redirect("/Personel/StokListesi");
        }

        //Veri tabanından stok silmek için yazmış olduğumuz bir controller methodur. silinecek olan stok id numrasını parametre olarak alır
        public IActionResult StokSil(int stokId)
        {
            BakkalDbContext context = new BakkalDbContext();
            //veri tabanında oluşturmuş olduğumuz stored procedure'lerden, seçmiş olduğumuz stoğun id bilgisini kullanarak veri tabanından stok silme işlemini yapacak olan procedürü çağırırız
            var data = context.Database.ExecuteSqlRaw($"proc_stok_delete {stokId}");
            return Redirect("/Personel/StokListesi");
        }
        public IActionResult StokListesi()
        {
            List<Stok> model = new List<Stok>();
            BakkalDbContext context = new BakkalDbContext();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden bize stok listesini dönecek olan procedürü çağırırız
            model = context.Stoks.FromSqlRaw<Stok>($"exec proc_stok_list").ToList();
            //Views'da bulunan StokListesi.cshtml dosyasına model bilgisi atılır.
            return View(model);
        }

        //Stok bilgilerini güncellemek için yazmış olduğumuz bir get http türlü controller methodur
        [HttpGet]
        public IActionResult StokGuncelle(int stokId)
        {
            BakkalDbContext context = new BakkalDbContext();
            Stok stock = new Stok();
            // veri tabanında oluşturmuş olduğumuz stored procedure'lerden, vermiş olduğumuz id bilgisine göre bize veri tabanında bulunan ilgili kayıdı getiren procedürü çağırırız
            stock = context.Stoks.FromSqlRaw($"exec proc_stok_get_by_id {stokId}").AsEnumerable().FirstOrDefault();
            //eğer herhangi bir stok kaydı bulunamamışsa sayfa bulunamadı döndürülür
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/Fatura.cshtml
@model BakkalUygulamasi.entity.Data.SatisMaddeleri
<div class="row">
    <h1 class="font-weight-light display-5 text-muted">Genel Satış Bilgileri</h1>
</div>
<hr>

<table class="table table-bordered table-sm mb-3">
    <thead style="background-color:#e6dc9d">
        <tr>
            <td style="width:170px;">Miktar</td>
            <td style="width:170px">Fiyat</td>
            <td style="width:170px;">İskonto</td>
            <td style="width:170px;">Toplam Fiyat</td>
        </tr>
    </thead>
    <tbody>
       
        <tr>

            <td>@Model.SiMiktar</td>
            <td>@Model.SiFiyat</td>
            <td>@Model.SiIskonto</td>
            <td>@Model.TotalFiyat()</td>
        </tr>
        
    </tbody>
</table>


<table class="table table-bordered table-sm mb-3">
    <thead style="background-color:#e6dc9d">
        <tr>
            <td style="width:170px;">Satış Tarihi</td>
            <td style="width:170px">Satış Durumu</td>
            <td style="width:170px;">Satış Yapan Kullanıcı Id</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Satis)
        {
            if (@item.SatisId == @Model.SatisId)
            {
                <tr>

                    <td>@item.STarih</td>
                    <td>@item.SDurum</td>
                    <td>@item.KullaniciId</td>
                </tr>
            }

        }
    </tbody>
</table>

<table class="table table-bordered table-sm mb-3">
    <thead style="background-color:#e6dc9d">
        <tr>
            <td style="width:170px;">Ürün Adı</td>
            <td style="width:170px">Ürün Barkodu</td>
            <td style="width:170px;">Ürün Üretim Tarihi</td>
            <td style="width:170px;">Ürün Tüketim Tarihi</td>
            <td style="width:170px;">Ürün Fiyatı</td>
            <td style="width:170px;">Ürün Ağırlığı</td>
            <td style="width:170px;">Ürün Rengi</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Uruns)
        {
            if (@item.UrunId == @Model.UrunId)
            {
            <tr>

                <td>@item.UAdi</td>
                <td>@item.UBarkodu</td>
                <td>@item.UUretimTarihi</td>
                <td>@item.UTuketimTarihi</td>
                <td>@item.UFiyat</td>
                <td>@item.UAgirlik</td>
                <td>@item.URengi</td>
              
            </tr>
            }
        }
    </tbody>
</table>
  

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/KategoriEkle.cshtml
@model BakkalUygulamasi.entity.Data.Kategori
<h1 class="h3 mt-4">Kategori Ekle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="KategoriEkle" method="POST">
                <div class="form-group row">
                    <label asp-for="@Model.KAdi" class=" col-form-label"><b>Kategori İsmi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.KAdi" />
                       
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/KategoriGuncelle.cshtml
@model BakkalUygulamasi.entity.Data.Kategori
<h1 class="h3 mt-4">Kategori Güncelle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="KategoriGuncelle" method="POST">
                <input type="hidden" name="KategoriId" value="@Model.KategoriId" />
                <div class="form-group row">
                    <label asp-for="@Model.KAdi" class=" col-form-label"><b>Kategori İsmi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.KAdi" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Güncelle</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/MarkaEkle.cshtml
@model BakkalUygulamasi.entity.Data.Marka
<h1 class="h3 mt-4">Marka Ekle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="MarkaEkle" method="POST">
                <div class="form-group row">
                    <label asp-for="@Model.MAdi" class="col-form-label"><b>Marka İsmi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.MAdi" />
                       
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/MarkaGuncelle.cshtml
@model BakkalUygulamasi.entity.Data.Marka
<h1 class="h3 mt-4">Marka Güncelle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="MarkaGuncelle" method="POST">
                <input type="hidden" name="MarkaId" value="@Model.MarkaId" />
                <div class="form-group row">
                    <label asp-for="@Model.MAdi" class=" col-form-label"><b>Marka İsmi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.MAdi" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Güncelle</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/SatisEkle.cshtml
@model BakkalUygulamasi.entity.Data.Sati
<h1 class="h3 mt-4">Satış Bilgileri Gir</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="SatisEkle" method="POST">

                <div class="form-group row">
                    <label asp-for="@Model.STarih" class="col-sm-2 col-form-label"><b>Satış Tarihi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.STarih" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.SDurum" class="col-sm-2 col-form-label "><b>Satış Durumu</b></label>
                    <div class="col-sm-10 ">
                        <input class="form-control" asp-for="@Model.SDurum" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.KullaniciId" class="col-sm-2 col-form-label "><b>Satış Yapan Kullanıcı Id</b></label>
                    <div class="col-sm-10 ">
                        <input class="form-control" asp-for="@Model.KullaniciId" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/SatisGuncelle.cshtml
@model BakkalUygulamasi.entity.Data.Sati
<h1 class="h3 mt-4">Satış Güncelle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="SatisGuncelle" method="POST">
                <input type="hidden" name="satisId" value="@Model.SatisId" />

                <div class="form-group row">
                    <label asp-for="@Model.STarih" class="col-sm-2 col-form-label"><b>Satış Tarihi</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.STarih" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.SDurum" class="col-sm-2 col-form-label"><b>Satış Durumu</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.SDurum" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.KullaniciId" class="col-sm-2 col-form-label "><b>Satış Yapan Kullanıcı Id</b></label>
                    <div class="col-sm-10 ">
                        <input class="form-control" asp-for="@Model.KullaniciId" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Güncelle</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}

BakkalUygulamasi/BakkalUygulamasi.webui/Views/Personel/SatisMaddeleriGuncelle.cshtml
@model BakkalUygulamasi.entity.Data.SatisMaddeleri
<h1 class="h3 mt-4">Ürün Satış Maddelerini Güncelle</h1>
<hr />
<div class="w-100">
    <div class="row">
        <div class="col-md-8">
            <form asp-controller="Personel" asp-action="SatisMaddeleriGuncelle" method="POST">
                <input type="hidden" name="smId" value="@Model.SmId" />
                <div class="form-group row">
                    <label asp-for="@Model.SiMiktar" class=" col-sm-2 col-form-label"><b>Satış Miktarı</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.SiMiktar" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.SiFiyat" class="col-sm-2 col-form-label "><b>Satış Fiyatı</b></label>
                    <div class="col-sm-10 ">
                        <input class="form-control" asp-for="@Model.SiFiyat" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.SiIskonto" class="col-sm-2 col-form-label"><b>Satış İskonto</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.SiIskonto" />

                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="@Model.SatisId" class=" col-sm-2 col-form-label"><b>Satış Id</b></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="@Model.SatisId" />

                    </div>
                </div>
                <div>
                    <label for="Marka">Ürün Seç</label>
                    @for (int i = 0; i < ViewBag.Uruns.Count; i++)
                    {
                        <input type="hidden" name="Uruns[@i].UrunId" value="@ViewBag.Uruns[@i].UrunId" />
                        <input type="hidden" name="Uruns[@i].UAdi" value="@ViewBag.Uruns[@i].UAdi" />}

                    <select asp-for="@Model.UrunId" class="col-sm-6 ml-5 mb-2 col-form-label">

                        @if (ViewBag.Uruns.Count > 0)
                        {
                            @foreach (var item in ViewBag.Uruns)
                            {
                                <option value="@item.UrunId">@item.UAdi</option>
                            }}
                    </select>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha512-UdIMMlVx0HEynClOIFSyOrPggomfhBKJE28LKl8yR3ghkgugPnG6iLfRfHwushZl1MOPSY6TsuBDGPK2X4zYKg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

}